### ISSUE TITLE
Rating Scale clarification

### ISSUE THREAD

**Issue by swrobel** [jackmullis/spitcast-api-docs#1]
Glad to see you have an open API again! I'm excited to dig into it for [Meta Surf Forecast](https://github.com/swrobel/meta-surf-forecast). I just wanted to clarify how you describe the rating scale:
> 0.0 = Poor, 0.5 = Poor-Fair, 1.0 = Fair, 1.5+ = Good

Does that mean that `shape` values can exceed 1.5, or is that the max value?

**Comment by jackmullis** [comment]
Ah, good catch.  Really it's >1.0 is Good.  I think it's possible to reach 3.0, but it's pretty unlikely you'll ever actually see it go that high.
